### ISSUE TITLE
Broken link in the page https://pybit.es/error_handling.html

### ISSUE THREAD

**Issue by vipinreyo** [pybites/pybites.github.io-src#6]
Hi Pybites
The "Little Book of Python Anti-Patterns link" 'http://docs.quantifiedcode.com/python-code-patterns/' is 404 not found. 

Cheers
Vipin

**Comment by pybites** [comment]
they moved it to https://docs.quantifiedcode.com/python-anti-patterns/
fixing link, thanks!
