### ISSUE TITLE
Regarding the Google spreadsheet and python twilio blog

### ISSUE THREAD

**Issue by vipinreyo** [pybites/pybites.github.io-src#7]
Hi Guys
I've tried to write a program based on  the blog https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html mentioned in your blog https://pybit.es/flask-api-part2.html, but the it threw a permission error. The solution is mentioned in https://github.com/burnash/gspread/issues/513. 

Since the comments for that blog is closed, it will be helpful if you can mention about it in the blog for the newbies.

Cheers
Vipin

**Comment by pybites** [comment]
Hey Vipin, sorry missed this. Feel free to clone https://github.com/pybites/pybites.github.io-src, and add the note as you experienced/worked around the issue, then create a PR for us to merge it in.
Thanks,
Bob
